export interface Food {
  id?: string; // Auto-generated by Firestore
  name: string;
  carbohydratesPerPortion: number; // Amount of carbs per portion (in grams)
  barcode?: string; // Optional barcode for scanning
}
