import { Food } from './food.model';

export interface MealLog {
  id?: string; // Auto-generated by Firestore
  userId: string; // Reference to User UID
  date: Date; // Timestamp of the meal
  foods: Food[]; // List of foods consumed
  totalCarbohydrates: number; // Total carbs for the meal
}
